[package]
name = "ssf-cmm"
description = "ssf to cmm compiler"
version = "0.1.0"
license = "MIT"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
cmm = { path = "../cmm" }
ssf = { path = "../ssf" }
