name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: raviqqe/ssf-ci
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@master
      - run: cargo release --token $CARGO_TOKEN
