name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: raviqqe/enable-homebrew@main
      - run: brew install llvm@14
      - uses: actions/checkout@v4
      - run: cargo test
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: raviqqe/enable-homebrew@main
      - run: brew install llvm@14
      - uses: actions/checkout@v4
      - run: cargo clippy -- -D warnings
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{md,rs}"
  code-coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: raviqqe/enable-homebrew@main
      - run: brew install llvm@14
      - uses: actions/checkout@v4
      - run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
          cargo llvm-cov --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
